apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component_name }}
  labels:
    app: {{ .Values.component_name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.component_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.component_name }}
    spec:
      containers:
        - name: {{ .Values.component_name }}
          image: 183295444327.dkr.ecr.us-east-1.amazonaws.com/${{ .Values.component_name }}:{{ .Values.imageTag }}
          envFrom:
            - configMapRef:
                name: {{ .Values.component_name }}
