apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .values.component_name }}
  labels:
    app: {{ .values.component_name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .values.component_name }}
  template:
    metadata:
      labels:
        app: {{  .values.component_name }}
    spec:
      containers:
        - name: {{ .values.component_name }}
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.component_name }}
          envFrom:
            - configMapRef:
                name: {{ .values.component_name}}
