{{ if .values.schema.enabled }}
{{- range .Values.schema.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.values.component_name }}-{{ . }}
spec:
  template:
    spec:
      containers:
        - name: schema-load
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          envFrom:
            - configMapRef:
                name: {{ $.values.component_name }}
          env:
            - name: SCHEMA_FILE
              value: db/{{ . }}.{{ $.values.schema.extension }}
      restartPolicy: Never
  backoffLimit: 4
{{ end }}
{{ end }}
