apiVersion: v1
Kind: Service
metadata:
  name: {{ .values.component_name }}
spec:
  type: {{ .values.service.type}}
  selector:
    component: {{ .values.component_name }}
  ports:
    - port: {{ .values.service.port}}
      targetPort: {{ .values.service.containerPort }}

